<?php
define('TITLE',         'Wiki'); 
define('AUTHOR',        'Vincent');
define('NOP',           'NOP');
define('USERID',        'UID');
define('USEREMAIL',     'UEMAIL');
define('USERNAME',      'UNAME');
define('USERROLE',      'UROLE');
define('CART',          'CART');
define('SYSMSG',        'SYSMSG');
define('SYSERR',        'SYSERR');
define('MYKEY',         '4711wwPxTT#^');
define('SRC',           '.\_src\\');
define('CLASSPATH',		'.\_src\classes\\');
define('LINKBASE',      'index.php?page=');
define('SHOPIMG_FOLDER','.\assets\shop\\');
define('WEBIMG_FOLDER', '.\assets\img\\');

define("PDOHOST",		"127.0.0.1");
define('PDODATABASE',   'educom_wiki');
define('PDOUSER',       'root');
define('PDOPASS',       '56787F62767E');
define('PDOPASSUNSAFE',  'WAMPsetup0191');
define('PDODRIVER',     'mysql');
